
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-batch-kitagry-github-io-v1alpha1-berglassecret
  failurePolicy: Fail
  name: kitagry.github.io
  rules:
  - apiGroups:
    - batch.kitagry.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - berglassecrets
  sideEffects: None
