
apiVersion: v1
kind: Service
metadata:
  name: berglas-secret-webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: berglas-secret-controller-manager
