// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/v1alpha1/berglassecret_webhook.go
//
// Generated by this command:
//
//	mockgen -source=./api/v1alpha1/berglassecret_webhook.go -destination=./api/v1alpha1/mock/berglas.go berglasClient
//

// Package mock_v1alpha1 is a generated GoMock package.
package mock_v1alpha1

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockberglasClient is a mock of berglasClient interface.
type MockberglasClient struct {
	ctrl     *gomock.Controller
	recorder *MockberglasClientMockRecorder
}

// MockberglasClientMockRecorder is the mock recorder for MockberglasClient.
type MockberglasClientMockRecorder struct {
	mock *MockberglasClient
}

// NewMockberglasClient creates a new mock instance.
func NewMockberglasClient(ctrl *gomock.Controller) *MockberglasClient {
	mock := &MockberglasClient{ctrl: ctrl}
	mock.recorder = &MockberglasClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockberglasClient) EXPECT() *MockberglasClientMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockberglasClient) Resolve(ctx context.Context, ref string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, ref)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockberglasClientMockRecorder) Resolve(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockberglasClient)(nil).Resolve), ctx, ref)
}
